controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_recipes:
    path: /api/recipes
    controller: App\Controller\RecipeController::fetchRecipes

api_ingredients:
    path: /api/ingredients/{recipeId}
    controller: App\Controller\IngredientController::fetchIngredients
