controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\HomeController::index

api_recipes:
    path: /api/recipes
    controller: App\Controller\RecipeController::fetchPageRecipes

api_ingredients:
    path: /api/ingredients
    controller: App\Controller\IngredientController::fetchAllIngredients

api_pages_number:
    path: /api/pagination
    controller: App\Controller\RecipeController::fetchNumberOfPages

api_author_recipes:
    path: /api/author/recipes
    controller: App\Controller\RecipeController::fetchAuthorRecipes

api_recipe_details:
    path: /api/recipe/details
    controller: App\Controller\RecipeController::fetchRecipeDetails

api_ingredients_common:
    path: /api/ingredients/common
    controller: App\Controller\IngredientController::fetchTopIngredients

api_authors_prolific:
    path: /api/authors/prolific
    controller: App\Controller\AuthorController::fetchProlificAuthors

api_recipes_complex:
    path: /api/recipes/complex
    controller: App\Controller\RecipeController::fetchComplexRecipes
