controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /home
    controller: App\Controller\HomeController::index

api_recipes:
    path: /api/recipes
    controller: App\Controller\RecipeController::fetchAllRecipes

api_ingredients:
    path: /api/ingredients
    controller: App\Controller\IngredientController::fetchAllIngredients

api_pages_number:
    path: /api/pagination
    controller: App\Controller\RecipeController::fetchNumberOfPages

api_author_recipes:
    path: /api/author/recipes
    controller: App\Controller\RecipeController::fetchAuthorRecipes
